"""Python CLI Golden Blueprint for Prompt2Product (docs/08 Faz 9).

Generates standalone, production-ready Python CLI applications using Typer and Rich.
"""
from pathlib import Path
from typing import Optional

from src.blueprints.base import Blueprint
from src.models.enums import TargetType
from src.models.project import ProjectSpec
from src.workspace.workspace import Workspace


class PythonCliBlueprint(Blueprint):
    """Golden blueprint for Python Command Line Interfaces (Typer + Rich)."""

    @property
    def name(self) -> str:
        return "python_cli"

    @property
    def targets(self) -> list[TargetType]:
        return [TargetType.CLI]

    def generate_scaffold(self, workspace: Workspace, spec: ProjectSpec) -> list[Path]:
        """Generates project scaffold for a Typer-powered CLI."""
        created_paths: list[Path] = []
        slug = spec.name.lower().replace(" ", "-").replace("_", "-")

        # 1. pyproject.toml
        desc = getattr(spec, "prompt", "A modern CLI application generated by Prompt2Product")
        pyproject_content = f"""[project]
name = "{slug}"
version = "0.1.0"
description = "{desc}"
requires-python = ">=3.10"
dependencies = [
    "typer>=0.12.0",
    "rich>=13.7.0",
    "pydantic>=2.7.0",
]

[project.scripts]
{slug} = "src.cli.main:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
"""
        p_toml = workspace.root_path / "pyproject.toml"
        p_toml.write_text(pyproject_content, encoding="utf-8")
        created_paths.append(p_toml)

        # 2. README.md
        readme_content = f"""# {spec.name}

{desc}

## Requirements
- Python 3.10+

## Quickstart
```bash
pip install -e .
{slug} --help
{slug} run "Hello World"
```
"""
        p_readme = workspace.root_path / "README.md"
        p_readme.write_text(readme_content, encoding="utf-8")
        created_paths.append(p_readme)

        # 3. Source directory: src/cli/__init__.py and src/cli/main.py
        cli_dir = workspace.root_path / "src" / "cli"
        cli_dir.mkdir(parents=True, exist_ok=True)

        p_cli_init = cli_dir / "__init__.py"
        p_cli_init.write_text('"""CLI Package."""\n', encoding="utf-8")
        created_paths.append(p_cli_init)

        main_py_content = f'''"""Entry point for {slug} CLI."""
import sys
import typer
from rich.console import Console
from rich.table import Table

app = typer.Typer(
    name="{slug}",
    help="{desc}",
    add_completion=False,
)
console = Console()


@app.command()
def version() -> None:
    """Print application version."""
    console.print("[bold green]{slug}[/bold green] version [cyan]0.1.0[/cyan]")


@app.command()
def run(
    query: str = typer.Argument(..., help="Input query to process"),
    verbose: bool = typer.Option(False, "--verbose", "-v", help="Enable verbose output"),
) -> None:
    """Execute main processing task."""
    console.print(f"[bold blue]Processing:[/bold blue] {{query}}")
    if verbose:
        console.print("[dim]Running in verbose mode...[/dim]")
    console.print("[bold green]Success:[/bold green] Completed task execution.")


@app.command()
def status() -> None:
    """Check CLI operational status."""
    table = Table(title="{slug} System Status")
    table.add_column("Component", style="cyan")
    table.add_column("Status", style="green")
    table.add_row("Core Engine", "OPERATIONAL")
    table.add_row("CLI Interface", "READY")
    console.print(table)


if __name__ == "__main__":
    app()
'''
        p_main = cli_dir / "main.py"
        p_main.write_text(main_py_content, encoding="utf-8")
        created_paths.append(p_main)

        # 4. Core logic: src/core/engine.py
        core_dir = workspace.root_path / "src" / "core"
        core_dir.mkdir(parents=True, exist_ok=True)

        p_core_init = core_dir / "__init__.py"
        p_core_init.write_text('"""Core business logic."""\n', encoding="utf-8")
        created_paths.append(p_core_init)

        engine_content = '''"""CLI Core Engine."""

class CoreEngine:
    """Core logic processor for CLI tasks."""

    def process(self, query: str) -> dict[str, str]:
        if not query or not query.strip():
            raise ValueError("Query cannot be empty")
        return {"query": query.strip(), "status": "processed"}
'''
        p_engine = core_dir / "engine.py"
        p_engine.write_text(engine_content, encoding="utf-8")
        created_paths.append(p_engine)

        return created_paths

    def generate_infra(self, workspace: Workspace, spec: ProjectSpec) -> list[Path]:
        """Generates container infrastructure for standalone execution."""
        created_paths: list[Path] = []
        slug = spec.name.lower().replace(" ", "-").replace("_", "-")

        dockerfile_content = f"""# Multi-stage non-root Python CLI image
FROM python:3.11-slim AS builder

WORKDIR /app
COPY pyproject.toml .
COPY src ./src
RUN pip install --no-cache-dir .

FROM python:3.11-slim AS runner

# Run as non-root user
RUN useradd -m -u 10001 appuser
USER appuser

WORKDIR /home/appuser
COPY --from=builder /usr/local /usr/local

ENTRYPOINT ["{slug}"]
CMD ["--help"]
"""
        p_docker = workspace.root_path / "Dockerfile"
        p_docker.write_text(dockerfile_content, encoding="utf-8")
        created_paths.append(p_docker)

        dockerignore_content = """.git
__pycache__
*.pyc
.venv
.pytest_cache
"""
        p_dignore = workspace.root_path / ".dockerignore"
        p_dignore.write_text(dockerignore_content, encoding="utf-8")
        created_paths.append(p_dignore)

        return created_paths

    def generate_tests(self, workspace: Workspace, spec: ProjectSpec) -> list[Path]:
        """Generates pytest test suite for the CLI application."""
        created_paths: list[Path] = []
        tests_dir = workspace.root_path / "tests"
        tests_dir.mkdir(parents=True, exist_ok=True)

        p_test_init = tests_dir / "__init__.py"
        p_test_init.write_text('"""CLI test suite."""\n', encoding="utf-8")
        created_paths.append(p_test_init)

        test_cli_content = '''"""Tests for CLI application."""
from typer.testing import CliRunner
from src.cli.main import app
from src.core.engine import CoreEngine
import pytest

runner = CliRunner()


def test_cli_help():
    result = runner.invoke(app, ["--help"])
    assert result.exit_code == 0
    assert "Usage" in result.output or "Options" in result.output


def test_cli_version():
    result = runner.invoke(app, ["version"])
    assert result.exit_code == 0
    assert "version" in result.output.lower()


def test_cli_run():
    result = runner.invoke(app, ["run", "test-command"])
    assert result.exit_code == 0
    assert "Processing:" in result.output
    assert "test-command" in result.output


def test_cli_status():
    result = runner.invoke(app, ["status"])
    assert result.exit_code == 0
    assert "OPERATIONAL" in result.output


def test_core_engine():
    engine = CoreEngine()
    res = engine.process("hello")
    assert res["status"] == "processed"
    assert res["query"] == "hello"

    with pytest.raises(ValueError):
        engine.process("   ")
'''
        p_test_file = tests_dir / "test_cli.py"
        p_test_file.write_text(test_cli_content, encoding="utf-8")
        created_paths.append(p_test_file)

        return created_paths
