"""Official Phase 9 Exit Criterion Test (docs/08 §Faz 9).

Exit Criterion:
1. Third-party runtime adapter can be registered and executed without touching core codebase.
2. grep / audit confirms zero hardcoded provider or model names in core packages (ADR-009 vendor independence).
3. ApiRuntime and OllamaRuntime successfully prove API and local offline execution models.
4. Second Golden Blueprint (python_cli) scaffolds standalone, testable CLI products.
5. a11y quality gate and p2p audit provide comprehensive quality and security verification.
"""
from pathlib import Path
import json
import re

from src.blueprints.python_cli import PythonCliBlueprint
from src.models.enums import TargetType, TaskOutcome, VerifiedBy
from src.models.project import ProjectSpec
from src.models.result import AgentResult
from src.models.task import AcceptanceCriterion, TaskContract
from src.plugins.registry import PluginRegistry, plugin_registry
from src.runtime.api import ApiRuntime
from src.runtime.base import RuntimeAdapter
from src.runtime.ollama import OllamaRuntime
from src.verification.a11y import A11yScanner
from src.verification.audit import ProjectAuditor
from src.workspace.workspace import Workspace


class ThirdPartyCustomRuntime(RuntimeAdapter):
    """External runtime registered dynamically by a third-party plugin developer."""

    def execute(self, contract: TaskContract, workspace: Path, run_id: str = None) -> AgentResult:
        output_file = workspace / "plugin_output.txt"
        output_file.write_text("Generated by third-party runtime plugin without touching core")
        return AgentResult(
            task_id=contract.id,
            run_id="ext-run-001",
            outcome=TaskOutcome.COMPLETED,
            summary="Third-party runtime completed execution seamlessly",
            files_changed=["plugin_output.txt"],
            criteria_addressed=[ac.id for ac in contract.acceptance_criteria],
            assumptions=["Zero modification to core engine"],
        )


def test_phase9_exit_criterion_extensibility_and_vendor_independence(tmp_path: Path):
    # 1. Extensibility: Dynamic registration without touching core
    plugin_registry.register_runtime("vllm_local", lambda **kwargs: ThirdPartyCustomRuntime())
    assert plugin_registry.has_runtime("vllm_local")

    ext_runtime = plugin_registry.get_runtime("vllm_local")
    from src.models.enums import Capability, EstimatedSize, RiskLevel

    contract = TaskContract(
        id="EXT-001",
        title="Test dynamic extension",
        capabilities=[Capability.BACKEND],
        risk=RiskLevel.LOW,
        intent="Verify plugin execution without modifying core.",
        acceptance_criteria=[AcceptanceCriterion(id="AC-1", statement="works", verified_by=VerifiedBy.MANUAL)],
        inputs=["docs/01"],
        allowed_paths=["plugin_output.txt", "*.txt"],
        forbidden_paths=[".p2p/**"],
        gates=["unit"],
        estimated_size=EstimatedSize.S,
        human_approval=True,
        result_path=".p2p/result.json",
        acr_path=".p2p/acr/",
    )
    res = ext_runtime.execute(contract, workspace=tmp_path)
    assert res.outcome == TaskOutcome.COMPLETED
    assert (tmp_path / "plugin_output.txt").exists()
    assert "without touching core" in (tmp_path / "plugin_output.txt").read_text()

    # 2. Vendor independence proof: Verify core packages do NOT hardcode model names
    repo_root = Path(__file__).resolve().parent.parent
    core_packages = ["orchestration", "planning", "workspace", "models"]
    model_regex = re.compile(r"\b(gpt-4o?|claude-3|gemini-1\.5|llama3)\b", re.IGNORECASE)

    violations = []
    for pkg in core_packages:
        pkg_dir = repo_root / "src" / pkg
        if not pkg_dir.exists():
            continue
        for p in pkg_dir.rglob("*.py"):
            lines = p.read_text(encoding="utf-8", errors="ignore").splitlines()
            for idx, line in enumerate(lines, 1):
                # Ignore comments, docstrings explaining ADRs, and enum test values
                if line.strip().startswith("#") or '"""' in line or "e.g." in line:
                    continue
                if model_regex.search(line):
                    violations.append(f"{p.name}:{idx} -> {line.strip()}")

    assert len(violations) == 0, f"Found vendor leakage in core packages: {violations}"

    # 3. ApiRuntime and OllamaRuntime operational proof
    api_runtime = ApiRuntime(
        endpoint="https://api.openai.mock/v1/chat/completions",
        api_key="mock-key",
        http_client=lambda u, p, h: {
            "choices": [{"message": {"content": json.dumps({"outcome": "completed", "files": {"api_out.txt": "api works"}})}}]
        },
    )
    api_res = api_runtime.execute(contract, workspace=tmp_path)
    assert api_res.outcome == TaskOutcome.COMPLETED
    assert (tmp_path / "api_out.txt").exists()

    ollama_runtime = OllamaRuntime(
        http_client=lambda u, p: {
            "message": {"content": json.dumps({"outcome": "completed", "files": {"ollama_out.txt": "ollama works"}})}
        }
    )
    ollama_res = ollama_runtime.execute(contract, workspace=tmp_path)
    assert ollama_res.outcome == TaskOutcome.COMPLETED
    assert (tmp_path / "ollama_out.txt").exists()

    # 4. Second Golden Blueprint (python_cli) verification
    cli_ws_dir = tmp_path / "cli_project"
    cli_ws_dir.mkdir()
    cli_ws = Workspace(cli_ws_dir)
    cli_ws.ensure_directories()

    bp = plugin_registry.get_blueprint("python_cli")
    assert bp is not None
    spec = ProjectSpec(name="data-sync", prompt="Data sync CLI", targets=[TargetType.CLI])
    scaffold = bp.generate_scaffold(cli_ws, spec)
    infra = bp.generate_infra(cli_ws, spec)
    tests = bp.generate_tests(cli_ws, spec)

    assert (cli_ws_dir / "pyproject.toml").exists()
    assert (cli_ws_dir / "Dockerfile").exists()
    assert (cli_ws_dir / "tests" / "test_cli.py").exists()

    # 5. a11y Gate and Security Audit
    a11y = A11yScanner()
    clean_markup = "<div><h1>Header</h1><button aria-label='Click'>Click</button></div>"
    assert len(a11y.scan_content(clean_markup)) == 0

    auditor = ProjectAuditor(cli_ws_dir)
    report = auditor.audit()
    assert report.passed is True
    assert report.critical_count == 0
